FROM adl-nni-base:latest

RUN apt-get -y install \
    automake \
    build-essential \
    cmake \
    curl \
    git \
    openssh-server \
    python3 \
    python3-dev \
    python3-pip \
    sudo \
    unzip \
    wget \
    zip

RUN ln -s python3 /usr/bin/python

RUN python3 -m pip --no-cache-dir install --upgrade pip
RUN python3 -m pip --no-cache-dir install setuptools wheel

RUN python3 -m pip --no-cache-dir install \
    lightgbm \
    numpy \
    pandas \
    scikit-learn \
    scipy \
    torch==1.10.2+cu102 \
    torchvision==0.11.3+cu102 \
    torchaudio==0.10.2+cu102 \
    --extra-index-url https://download.pytorch.org/whl/cu102

RUN python3 -m pip --no-cache-dir install pytorch-lightning

RUN python3 -m pip --no-cache-dir install tensorflow

RUN python3 -m pip --no-cache-dir install azureml==0.2.7 azureml-sdk==1.38.0

RUN python3 -m pip install nni==2.6.1

WORKDIR /root
